"""
portfolio.py

Simulates a trading portfolio for backtesting purposes.

Responsibilities
----------------
- Track available cash
- Track current position (number of shares)
- Process trading signals (BUY/SELL)
- Maintain a log of executed trades
- Compute total portfolio value over time

Execution Model
---------------
- Trades are executed immediately at the bar's close price
- No slippage or latency is modeled
- No commissions or fees are included (yet)

This is a simplified simulation intended for:
- validating strategy logic
- building the backtesting pipeline

NOT intended for production-grade backtesting accuracy.
"""


class Portfolio:
    """
    Represents a simulated trading portfolio.

    Attributes
    ----------
    cash : float
        Current available cash balance.

    position : int
        Current number of shares held.
        - 0 means no position
        - positive value means long position

    trade_log : list
        List of executed trades.
        Each entry is a tuple:
        (action, price, quantity)

    Notes
    -----
    - This implementation only supports long positions (no shorting)
    - Position sizing is determined entirely by the strategy
    - Risk management is not enforced here
    """

    def __init__(self, starting_cash: float = 10000):
        """
        Initialize the portfolio.

        Parameters
        ----------
        starting_cash : float, optional
            Initial capital for the backtest.
            Default is 10,000.
        """
        self.cash = starting_cash
        self.position = 0
        self.trade_log = []

    def process_signal(self, signal: dict | None, bar: dict) -> None:
        """
        Process a trading signal and update portfolio state.

        Parameters
        ----------
        signal : dict or None
            Trading signal generated by a strategy.
            Expected format:
            {
                "action": "BUY" | "SELL",
                "quantity": int
            }

            If None, no action is taken.

        bar : dict
            Market data for the current time step.
            Must contain:
            - "close" (used as execution price)

        Behavior
        --------
        - BUY:
            * Checks if sufficient cash is available
            * Deducts cash and increases position

        - SELL:
            * Checks if sufficient shares are held
            * Increases cash and reduces position

        - If constraints are not met:
            * Signal is ignored (no partial fills)

        Notes
        -----
        - All trades are executed at the bar's closing price
        - No transaction costs are applied
        - No partial fills are supported
        """
        if signal is None:
            return

        price = bar["close"]
        quantity = signal["quantity"]
        action = signal["action"]

        if action == "BUY":
            cost = price * quantity

            # Ensure sufficient cash
            if self.cash >= cost:
                self.cash -= cost
                self.position += quantity

                self.trade_log.append(("BUY", price, quantity))

        elif action == "SELL":
            # Ensure sufficient position
            if self.position >= quantity:
                self.cash += price * quantity
                self.position -= quantity

                self.trade_log.append(("SELL", price, quantity))

    def get_value(self, current_price: float) -> float:
        """
        Calculate total portfolio value.

        Parameters
        ----------
        current_price : float
            The current market price of the asset.

        Returns
        -------
        float
            Total portfolio value:
            cash + (position * current_price)

        Notes
        -----
        - This represents mark-to-market valuation
        - Assumes positions can be liquidated at current_price
        """
        return self.cash + (self.position * current_price)
