#!/usr/bin/env python3
"""
Market making bid/offer generator driven by implied settlement prices.

Bids and offers are placed 5% away from the current implied_settlement; they are
updated and written to CSV each time a new implied settlement is generated by the
settlement engine (on each LMP or SPP15 update).

Usage (from repo root):
    python -m front_hour_pricing.market_making_orders <lmp5_csv_path> <spp15_csv_path> [--output path]

Output CSV is written to the Downloads folder by default (or --output path).
Columns: timestamp_utc, hub, settlement_date, hour_ending, implied_settlement, bid, offer
"""

from __future__ import annotations

import argparse
import csv
import logging
import sys
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any, Optional

from ercot.settlement_calculator import RollingEstimate, SettlementEngine

from run_settlement_test_data import load_and_merge_events

logger = logging.getLogger(__name__)

# Base spread: 5% each side of implied when all 4 SPP15s are confirmed
BID_OFFER_SPREAD_PCT = 0.05
# When 0 SPP15s confirmed, spread widens by this multiplier; linear scale down to 1.0 at 4 confirmed
N_INTERVALS = 4
SPREAD_MULTIPLIER_MAX = 5.0
# After mid-hour SPP15 confirmation (:15/:30/:45), wait up to this many ms for next LMP before publishing
SPP_CONFIRM_HOLD_MS_DEFAULT = 25_000  # at 0 confirmed, spread is 2x base (10% each side)


def _spread_multiplier(confirmed_spp_count: int) -> float:
    """Scale from SPREAD_MULTIPLIER_MAX (0 confirmed) down to 1.0 (4 confirmed). Linear in unfilled slots."""
    unfilled = N_INTERVALS - min(max(confirmed_spp_count, 0), N_INTERVALS)
    return 1.0 + (SPREAD_MULTIPLIER_MAX - 1.0) * (unfilled / N_INTERVALS)


def bid_offer_from_implied(
    implied_settlement: float,
    confirmed_spp_count: Optional[int] = None,
) -> tuple[float, float]:
    """
    Return (bid, offer) around implied settlement.

    Base spread is BID_OFFER_SPREAD_PCT (5%) each side. When confirmed_spp_count
    is provided (0–4), the spread widens when fewer SPP15s are confirmed: widest
    at 0, normal at 4. This reduces first-tick overconfidence.
    """
    if confirmed_spp_count is None:
        mult = 1.0
    else:
        mult = _spread_multiplier(confirmed_spp_count)
    half = BID_OFFER_SPREAD_PCT * mult
    bid = round(implied_settlement * (1 - half), 4)
    offer = round(implied_settlement * (1 + half), 4)
    return bid, offer


def get_downloads_path() -> Path:
    """Return the user's Downloads folder (Windows or Unix). Override with env MARKET_MAKING_CSV_DIR."""
    import os
    if os.environ.get("MARKET_MAKING_CSV_DIR"):
        return Path(os.environ["MARKET_MAKING_CSV_DIR"])
    return Path.home() / "Downloads"


CSV_HEADER = [
    "timestamp_utc",
    "hub",
    "settlement_date",
    "hour_ending",
    "implied_settlement",
    "bid",
    "offer",
]


def ensure_csv_header(csv_path: Path) -> None:
    """Create file with header if it does not exist."""
    if not csv_path.exists():
        csv_path.parent.mkdir(parents=True, exist_ok=True)
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(CSV_HEADER)


def reset_csv_for_run(csv_path: Path) -> None:
    """Truncate the CSV and write only the header. Call at start of each run so reruns overwrite."""
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(CSV_HEADER)


def write_bid_offer_row(
    csv_path: Path,
    timestamp: datetime,
    hub: str,
    settlement_date: date,
    hour_ending: int,
    implied_settlement: float,
    bid: float,
    offer: float,
) -> None:
    """Append one row to the market making bids CSV."""
    ensure_csv_header(csv_path)
    with open(csv_path, "a", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow([
            timestamp.isoformat(),
            hub,
            settlement_date.isoformat(),
            hour_ending,
            f"{implied_settlement:.4f}",
            f"{bid:.4f}",
            f"{offer:.4f}",
        ])


def on_estimate(
    csv_path: Path,
    estimate: RollingEstimate,
    hub: str,
    settlement_date: date,
    hour_ending: int,
) -> None:
    """Compute bid/offer from estimate and append to CSV. Spread widens when fewer SPP15s confirmed."""
    bid, offer = bid_offer_from_implied(
        estimate.implied_settlement,
        confirmed_spp_count=estimate.intervals_realized,
    )
    write_bid_offer_row(
        csv_path,
        estimate.timestamp,
        hub,
        settlement_date,
        hour_ending,
        estimate.implied_settlement,
        bid,
        offer,
    )
    # logger.debug(
    #     f"{hub} {settlement_date} HE{hour_ending} "
    #     f"implied={estimate.implied_settlement:.4f} bid={bid:.4f} offer={offer:.4f}"
    # )


def _flush_held(
    engine: SettlementEngine,
    held: dict[tuple[str, int], dict[str, Any]],
    csv_path: Path,
) -> None:
    """Publish latest estimate for each held (hub, he) and clear the hold."""
    for (hub, hour_ending), info in list(held.items()):
        est = engine.latest_estimate(hub, hour_ending)
        if est is not None:
            on_estimate(csv_path, est, hub, info["settlement_date"], hour_ending)
        del held[(hub, hour_ending)]


def run_engine_with_bid_offer(
    events: list,
    engine: SettlementEngine,
    csv_path: Path,
    spp_confirm_hold_ms: int = SPP_CONFIRM_HOLD_MS_DEFAULT,
) -> None:
    """Feed events into the engine; write bid/offer to CSV after each update.

    For mid-hour SPP15 confirmations (:15/:30/:45), holds publish for up to
    spp_confirm_hold_ms to allow the next LMP to arrive; final (:00) publishes immediately.
    """
    held: dict[tuple[str, int], dict[str, Any]] = {}  # (hub, he) -> {deadline, settlement_date}

    for ev in events:
        ts, kind, payload = ev
        hub = payload["hub"]
        hour_ending = payload["hour_ending"]
        settlement_date = payload["settlement_date"]
        key = (hub, hour_ending)

        # LMP arrived while we were holding for this key → use it and publish once
        if kind == "lmp" and key in held:
            result = engine.update_rt_lmp(
                hub=hub,
                hour_ending=hour_ending,
                lmp=payload["lmp"],
                as_of=payload["as_of"],
            )
            if result is not None:
                on_estimate(csv_path, result, hub, settlement_date, hour_ending)
            del held[key]
            continue

        # Flush any held keys whose deadline has passed (current event time >= deadline)
        for (h, he), info in list(held.items()):
            if ts >= info["deadline"]:
                est = engine.latest_estimate(h, he)
                if est is not None:
                    on_estimate(csv_path, est, h, info["settlement_date"], he)
                del held[(h, he)]

        # Process current event
        if kind == "lmp":
            result = engine.update_rt_lmp(
                hub=hub,
                hour_ending=hour_ending,
                lmp=payload["lmp"],
                as_of=payload["as_of"],
            )
            if result is not None:
                on_estimate(csv_path, result, hub, settlement_date, hour_ending)
        else:
            result = engine.confirm_spp15(
                hub=hub,
                hour_ending=hour_ending,
                interval_num=payload["interval_num"],
                spp15=payload["spp15"],
                confirmed_at=payload["confirmed_at"],
            )
            if result is not None:
                if result.intervals_remaining == 0:
                    # Final (:00) confirmation — publish immediately
                    on_estimate(csv_path, result, hub, settlement_date, hour_ending)
                else:
                    # Mid-hour (:15/:30/:45) — hold for next LMP up to spp_confirm_hold_ms
                    held[key] = {
                        "deadline": ts + timedelta(milliseconds=spp_confirm_hold_ms),
                        "settlement_date": settlement_date,
                    }

    # Flush any remaining held (e.g. no LMP arrived before end of replay)
    _flush_held(engine, held, csv_path)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate market making bids/offers (5%% from implied) and write to CSV."
    )
    parser.add_argument(
        "lmp5_csv",
        help="Path to your LMP5 data file (5-min RT LMP CSV), e.g. /mnt/c/Users/Kyle/Downloads/<filename>.csv",
    )
    parser.add_argument(
        "spp15_csv",
        help="Path to your SPP15 data file (15-min settlement CSV), e.g. /mnt/c/Users/Kyle/Downloads/<filename>.csv",
    )
    parser.add_argument("--hub", default="HB_NORTH", help="Hub to filter")
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Output CSV path (default: Downloads/market_making_orders.csv)",
    )
    parser.add_argument(
        "--spp-confirm-hold-ms",
        type=int,
        default=SPP_CONFIRM_HOLD_MS_DEFAULT,
        metavar="MS",
        help="After mid-hour SPP15 confirm (:15/:30/:45), wait up to MS ms for next LMP before publishing (default: %(default)s)",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="DEBUG logging")
    args = parser.parse_args()

    def resolve_input_path(path: Path, label: str) -> Path:
        if path.exists():
            return path
        if not path.is_absolute():
            candidates = [
                get_downloads_path() / path.name,
                Path("/mnt/c/Users/Kyle/Downloads") / path.name,  # WSL Windows Downloads
            ]
            for candidate in candidates:
                if candidate.exists():
                    return candidate
        tried = [path.resolve()] + (
            [get_downloads_path() / path.name, Path("/mnt/c/Users/Kyle/Downloads") / path.name]
            if not path.is_absolute() else []
        )
        raise SystemExit(
            f"{label} not found: {path}\n"
            "Tried: " + ", ".join(str(p) for p in tried) + "\n"
            "Use the full path (e.g. /mnt/c/Users/Kyle/Downloads/lmp5.csv) or put files in one of the above."
        )

    lmp5_path = resolve_input_path(Path(args.lmp5_csv), "LMP5 CSV")
    spp15_path = resolve_input_path(Path(args.spp15_csv), "SPP15 CSV")

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
        datefmt="%H:%M:%S",
        stream=sys.stdout,
    )

    csv_path = Path(args.output) if args.output else (get_downloads_path() / "market_making_orders.csv")
    logger.info(f"Writing bid/offer rows to {csv_path}")

    events = load_and_merge_events(str(lmp5_path), str(spp15_path), hub_filter=args.hub)
    logger.info(f"Loaded {len(events)} events for {args.hub}")

    by_date: dict[date, list] = {}
    for ev in events:
        d = ev[2]["settlement_date"]
        by_date.setdefault(d, []).append(ev)
    days_sorted = sorted(by_date.keys())
    logger.info(f"Processing {len(days_sorted)} day(s): {days_sorted[0]} through {days_sorted[-1]}")

    reset_csv_for_run(csv_path)  # fresh file each run so reruns overwrite

    for d in days_sorted:
        day_events = by_date[d]
        engine = SettlementEngine(hubs=[args.hub])
        run_engine_with_bid_offer(
            day_events, engine, csv_path, spp_confirm_hold_ms=args.spp_confirm_hold_ms
        )

    with open(csv_path, "r", encoding="utf-8") as f:
        row_count = sum(1 for _ in f) - 1  # minus header
    logger.info(f"Wrote {row_count} bid/offer rows to {csv_path}")
    print(f"\nMarket making bids/offers written to: {csv_path}")


if __name__ == "__main__":
    main()
